### ISSUE TITLE
关于googlemap.js的改进

### ISSUE THREAD

**Issue by riddle911** [pasu/ExamplesforCesium#1]
大佬，我昨天研究了一下openstreetmap的调用js，也看了您写的googlemap.js的插件。
有以下想法：
0.首先我拿到的google无偏影像图源是这样的，
`<url><![CDATA[http://mt{$serverpart}.google.cn/vt/lyrs=s&hl=zh-CN&x={$x}&y={$y}&z={$z}]]></url>`
`<serverParts>0 1 2 3</serverParts>`

1.osm和googlemap的切片方式都是相同的，都是直接加载的xyz形式图源。有没有什么办法能通过修改creatosm这个官方库达到加载google无偏影像的做法呢，然而这样做是不是涉及修改源代码，还要再进行编译呢。
2.关于googlemap.js，我看到您调用的地址也是xyz格式，带了一个key，恕我太渣，并没有看懂是个怎么调用的，昨晚试图修改成我自己的xyz图源，也没有成功...您看我上面提供的这个图源地址能否直接带入您修改的插件呢。

比较疑惑的是leaflet这样轻量级的库都可以原生支持xyz图源，而大哥cesium确没有这个玩意儿，有点儿蛋疼。
还请您不吝赐教~

**Comment by pasu** [comment]
根据你提供的url，对应的为google maps url，效果如下：
https://pasu.github.io/ExamplesforCesium/examples/editor.html#02_googlemaps
对应的实现代码在这：
https://github.com/pasu/ExamplesforCesium/blob/master/examples/js/googlemaps.js

**Comment by riddle911** [comment]
厉害了老哥~虽然closed我还是得回复下 谢谢哥。
然后还得说句，早上我刚给您提了issue，又搜到了一个cartodb他们写的插件，貌似很精简，
https://github.com/CartoDB/cesium-cartodb
地址在这，您看看。cartodb也是xyz图源，他是从osm那个库直接剥离过来的，我同样试着把mt1.google.cn/vt/lyrs=s&hl=zh-CN&x={x}&y={y}&z={z}这个地址试图替换进去，然而网页运行以后，他总是在这个图源地址后自动加一个‘/’，然后这个资源就400了。我试图解决了一早上也没有办法，刚才看到您的update，想想先参考您的思路往下做吧。
再说声谢谢啦！
