### ISSUE TITLE
你好，请问使用天地图的标注服务可以只要城市部分的标注吗？

### ISSUE THREAD

**Issue by lzio** [pasu/ExamplesforCesium#4]

**Comment by pasu** [comment]
你可以先看看天地图的注记，城市级别的标注对应的level的范围，然后在创建的天地图的服务中，指定对应的minimumLevel和maximumLevel，这样就可以控制只显示城市范围的标注。
这个是我的思路，可能会有一些小问题，比如需要控制超出level下，对应的天地图provider透明，避免拉伸的情况
