### ISSUE TITLE
大神，能帮忙看看如何解码rest接口获取的地理元素吗/need help on encoding geometry

### ISSUE THREAD

**Issue by kathur2rain** [pasu/ExamplesforCesium#6]
您好，我阅读了您在i3sdownloader.py 中的代码， 但是没有找到在rest接口中通过 ./nodes/0/geometries/0  获取二进制的地理元素， 然后解码的相关代码， 似乎是二进制的geometry 可以直接用于 scenelayer 渲染？ 如果我想还原这部分3d数据，应该如何操作呢？
我在i3s的 specification 中找到了 关于geometry 部分的描述， 不过仍然不清楚应该如何操作才能获得我们通用的 三维 obj 或者是 ewkt 之类的数据。
https://github.com/Esri/i3s-spec/blob/master/docs/1.7/IntegratedMesh_ReadMe.md
不知道您是否能提供一些建议？

hi, I just read your code in i3sdownloader.py, but not lucky, I didn't find code on decoding binary data of geometries from restapi. Could you have a look?

**Comment by pasu** [comment]
你说的这个工作属于之前我在公司的工作内容，所以没法说，而且时间很久了，已经记不清楚了。我当时是调试esri的js api，然后找到的解析格式的规范。另外，这个事情我觉得没太多意义，我觉得这个设计很复杂，数据性能很低，比如需要投影转换等。仅供参考，不太有帮助。

**Comment by kathur2rain** [comment]
还是谢谢您！
