### ISSUE TITLE
How to get these two parameters？

### ISSUE THREAD

**Issue by gangxuexue** [pasu/ExamplesforCesium#7]
How to get these two parameters from lonlat(180,90)？     
 let height = 33746824;
 let width = 33554054;

**Comment by pasu** [comment]
？

**Comment by gangxuexue** [comment]
目录在ExamplesforCesium/examples/baidu.html，修正百度地图瓦片算法（坐标有偏移）的demo中有两个参数一个height为33746824，一个width为33554054,这两个参数是如何获得的？
