### ISSUE TITLE
百度地图demo，中的height和width如何确定？

### ISSUE THREAD

**Issue by gangxuexue** [pasu/ExamplesforCesium#8]
目录在ExamplesforCesium/examples/baidu.html，里面有一个cesium对接百度地图的例子，我发现有两个参数let height = 33746824;let width = 33554054;这个是如何来的？

**Comment by pasu** [comment]
猜的，不小心猜对了。
百度地图的切片起始点（x=0,y=0）是经纬度的0，0，而其他的地图起始点都是左上角，所以需要偏移到对应的位置，这个值正好能近似的对齐。基于这个原理，反算出来的这个值，作为左上角点的米单位
